### ISSUE TITLE
better can we grab ball + displayed on vision feed?

### ISSUE THREAD

**Issue by Ramsey144** [Ramsey144/SDP-2016-9E#33]
yeah for our robots i was thinking we could have a little area displayed on the vision feed for where the grab range is supposed to be - mostly for eyeball testing to see if it looks reasonable.

also separate 'can we grab ball' vs 'do we have ball' functions would be helpful

**Comment by jsren** [comment]
> Displayed on vision feed?

**Comment by Ramsey144** [comment]
yeah for our robots i was thinking we could have a little area displayed on the vision feed for where the grab range is supposed to be - mostly for eyeball testing to see if it looks reasonable

**Comment by Ramsey144** [comment]
this will be robot dependent i guess

**Comment by jsren** [comment]
Sounds good!

**Comment by Ramsey144** [comment]
also separate can we grab ball vs do we have ball would be helpful
