### ISSUE TITLE
logging/scrolling for the launcher

### ISSUE THREAD

**Issue by Ramsey144** [Ramsey144/SDP-2016-9E#36]
at the moment, all information printed to standard out and standard error is lost once the launcher window overflows, or if the curses display crashes - a logging system would be great to aid testing and debugging

**Comment by Ramsey144** [comment]
a scrolling launcher window would be even nicer, although logging would still be great for debugging after crashes

**Comment by jsren** [comment]
@Ramsey144: Just a thought - any point in adding a new 'Logging' tab to the vision UI alongside an interface call `vision.log("This is Patrick", INFO)`? Maybe a big text box, with scrollbar, and a 'Clear' button to empty it?

**Comment by Ramsey144** [comment]
yes pls! i think scrolling in tkinter will be a lot easier than scrolling in curses

**Comment by jsren** [comment]
See also https://github.com/jsren/sdp-vision/issues/18
