### ISSUE TITLE
Better calibration for the ball IR sensor

### ISSUE THREAD

**Issue by Ramsey144** [Ramsey144/SDP-2016-9E#59]
Needs to work better, for both rooms and with no false positives.

**Comment by nkaki** [comment]
put the IR sensor lower

**Comment by nkaki** [comment]
Room 0,
No ball, [-79,-64]
Ball, [-40,-30]

**Comment by nkaki** [comment]
Room 0,
No ball, [-80,-60]
Ball, [-40,-30]

**Comment by nkaki** [comment]
Room 1,
No ball, [-70,-60]
Ball, [-37,-30]

**Comment by nkaki** [comment]
Threshold about 50 for both room i guess?
